### ISSUE TITLE
Bot not recognizing valid token

### ISSUE THREAD

**Issue by ItsLuiggiYahoo** [Polytoria/VerifyBot#7]
```• [Bot] Loggin in...
Promise {
  <rejected> Error [TokenInvalid]: An invalid token was provided.
      at Client.login (/home/runner/VerifyBot/node_modules/discord.js/src/client/Client.js:216:52)
      at file:///home/runner/VerifyBot/dist/index.js:85:8
      at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
      at async Promise.all (index 0)
      at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
      at async loadESM (node:internal/process/esm_loader:91:5)
      at async handleMainPromise (node:internal/modules/run_main:65:12) {
    code: 'TokenInvalid'
  }
}
✅ [Firebase] Successfully Connected to firebase!```

I've resetted the token 5 times and nothing...

**Comment by StarManTheGamer** [comment]
This has to do with you and isn't an issue with the bot. Please verify that you attached the token inside of the .env file.

**Comment by ItsLuiggiYahoo** [comment]
> This has to do with you and isn't an issue with the bot. Please verify that you attached the token inside of the .env file.

Yes it was, And I even changed the client.login to be only the token and it didn't work.

**Comment by StarManTheGamer** [comment]
The bot doesn't use client.login.
Please create a file called .env and use this format:
TOKEN=token

**Comment by ItsLuiggiYahoo** [comment]
> The bot doesn't use client.login.
> Please create a file called .env and use this format:
> TOKEN=token
> 

Oh, ok, I wonder what I changed...

Question, do I need to run npm run build before every change?

**Comment by IndexingGitHub** [comment]
> > The bot doesn't use client.login.
> > Please create a file called .env and use this format:
> > TOKEN=token
> 
> Oh, ok, I wonder what I changed...
> 
> Question, do I need to run npm run build before every change?

I believe so. 
`npm run build` to build
then
`npm run start` to start bot or update to new build
